#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aufs-util
Version  : 09a46dd640afeca9871f35b9bddc51d31f3a5f0d
Release  : 2
URL      : https://sourceforge.net/code-snapshots/git/a/au/aufs/aufs-util.git/aufs-aufs-util-09a46dd640afeca9871f35b9bddc51d31f3a5f0d.zip
Source0  : https://sourceforge.net/code-snapshots/git/a/au/aufs/aufs-util.git/aufs-aufs-util-09a46dd640afeca9871f35b9bddc51d31f3a5f0d.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: aufs-util-bin
Requires: aufs-util-lib
Requires: aufs-util-doc
BuildRequires : glibc-staticdev
Patch1: 0001-use-_DEFAULT_SOURCE-instead-of-_BSD_SOURCE.patch
Patch2: 0002-enable-kernel-headers-on-source.patch
Patch3: 0003-remove-change-ownership.patch

%description
Utilities for aufs
http://aufs.sf.net
Junjiro R. Okajima
These utilities are always necessary for aufs.
If you forget to install them, your aufs may not work correctly.
And these are not for aufs1 essentially, except aubrsync. See below in
detail.

%package bin
Summary: bin components for the aufs-util package.
Group: Binaries

%description bin
bin components for the aufs-util package.


%package dev
Summary: dev components for the aufs-util package.
Group: Development
Requires: aufs-util-lib
Requires: aufs-util-bin
Provides: aufs-util-devel

%description dev
dev components for the aufs-util package.


%package doc
Summary: doc components for the aufs-util package.
Group: Documentation

%description doc
doc components for the aufs-util package.


%package lib
Summary: lib components for the aufs-util package.
Group: Libraries

%description lib
lib components for the aufs-util package.


%prep
%setup -q -n aufs-aufs-util-09a46dd640afeca9871f35b9bddc51d31f3a5f0d
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/aubrsync
/usr/bin/aubusy
/usr/bin/auchk
/usr/bin/auibusy
/usr/bin/aumvdown
/usr/bin/auplink
/usr/bin/mount.aufs
/usr/bin/umount.aufs

%files dev
%defattr(-,root,root,-)
/usr/lib/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib/*.so.*
